name: Yarn ESLint

on:
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: yarn install
      - name: Run ESLint
        run: yarn lint .
      
